export ZSH=~/.oh-my-zsh

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH

ZSH_THEME="bureau"

plugins=(git composer vagrant laravel5)

source $ZSH/oh-my-zsh.sh

alias tigref="git reflog --pretty=raw | tig --pretty=raw"
alias local_smtp='python -m smtpd -n -c DebuggingServer localhost:1025'
