export PATH="/usr/local/bin:/Users/nick/bin:$PATH"
export ZSH=~/.oh-my-zsh

ZSH_THEME="bureau"

plugins=(git rvm node rvm ubuntu composer docker go httpie laravel4 laravel5 npm bower virtualenv vagrant docker-compose pip pep8 sudo frontend-search git-extras httpie)

source $ZSH/oh-my-zsh.sh

[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm" 
[ -s "$HOME/.dnx/dnvm/dnvm.sh" ] && . "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm


alias tigref="git reflog --pretty=raw | tig --pretty=raw"
