export ZSH=~/.oh-my-zsh

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

ZSH_THEME="af-magic"
export EDITOR=vim

source $ZSH/oh-my-zsh.sh

alias tigref="git reflog --pretty=raw | tig --pretty=raw"
alias local_smtp='python -m smtpd -n -c DebuggingServer localhost:1025'
alias nick='cd /mnt/c/Users/Nick/'
export DOCKER_HOST='tcp://0.0.0.0:2375'

#Change ls colours
LS_COLORS="ow=01;36;40" && export LS_COLORS
#
##make cd use the ls colours
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
